package ai.docling.serve.api.chunk.request;

import java.util.List;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

import ai.docling.serve.api.chunk.request.options.HierarchicalChunkerOptions;
import ai.docling.serve.api.convert.request.options.ConvertDocumentOptions;
import ai.docling.serve.api.convert.request.source.Source;
import ai.docling.serve.api.convert.request.target.Target;

/**
 * Represents a request to convert a document and chunk it into smaller documents
 * using the Docling hierarchical chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = HierarchicalChunkDocumentRequest.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class HierarchicalChunkDocumentRequest {

  /**
   * List of input document sources to process.
   *
   * @param sources the list of document sources
   * @return the list of document sources
   */
  @JsonProperty("sources")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Source> sources;

  /**
   * Conversion options.
   *
   * @param options the conversion options
   * @return the conversion options
   */
  @JsonProperty("convert_options")
  @lombok.NonNull
  @lombok.Builder.Default
  private ConvertDocumentOptions options = ConvertDocumentOptions.builder().build();

  /**
   * Specification for the type of output target.
   *
   * @param target the output target specification, or null if not specified
   * @return the output target specification, or null if not specified
   */
  @JsonProperty("target")
  @Nullable
  private Target target;

  /**
   * If true, the output will include both the chunks and the converted document.
   *
   * @param includeConvertedDoc true if the converted document should be included, false otherwise
   * @return true if the converted document should be included, false otherwise
   */
  @JsonProperty("include_converted_doc")
  private boolean includeConvertedDoc;

  /**
   * Options specific to the chunker.
   *
   * @param chunkingOptions the hierarchical chunker options
   * @return the hierarchical chunker options
   */
  @JsonProperty("chunking_options")
  @lombok.NonNull
  @lombok.Builder.Default
  private HierarchicalChunkerOptions chunkingOptions = HierarchicalChunkerOptions.builder().build();

  /**
   * Builder for creating {@link HierarchicalChunkDocumentRequest} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code source(Source)} - Add a single document source (use with @Singular)</li>
   *   <li>{@code sources(List<Source>)} - Set the list of document sources</li>
   *   <li>{@code options(ConvertDocumentOptions)} - Set the conversion options</li>
   *   <li>{@code target(Target)} - Set the output target specification</li>
   *   <li>{@code includeConvertedDoc(boolean)} - Set whether to include converted document</li>
   *   <li>{@code chunkingOptions(HierarchicalChunkerOptions)} - Set the hierarchical chunker options</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
