package ai.docling.serve.api.chunk.request;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import ai.docling.serve.api.chunk.request.options.HybridChunkerOptions;

/**
 * Represents a request to convert a document and chunk it into smaller documents
 * using the Docling hybrid chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = HybridChunkDocumentRequest.BuilderImpl.class)
@lombok.extern.jackson.Jacksonized
@lombok.experimental.SuperBuilder(toBuilder = true)
@lombok.Getter
@lombok.ToString(callSuper = true)
public final class HybridChunkDocumentRequest extends ChunkDocumentRequest {
  /**
   * Options specific to the chunker.
   *
   * @param chunkingOptions the hybrid chunker options
   * @return the hybrid chunker options
   */
  @JsonProperty("chunking_options")
  @lombok.NonNull
  @lombok.Builder.Default
  private HybridChunkerOptions chunkingOptions = HybridChunkerOptions.builder().build();

  /**
   * Builder for creating {@link HybridChunkDocumentRequest} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code source(Source)} - Add a single document source (use with @Singular)</li>
   *   <li>{@code sources(List<Source>)} - Set the list of document sources</li>
   *   <li>{@code options(ConvertDocumentOptions)} - Set the conversion options</li>
   *   <li>{@code target(Target)} - Set the output target specification</li>
   *   <li>{@code includeConvertedDoc(boolean)} - Set whether to include converted document</li>
   *   <li>{@code chunkingOptions(HybridChunkerOptions)} - Set the hybrid chunker options</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static abstract class HybridChunkDocumentRequestBuilder extends ChunkDocumentRequest.ChunkDocumentRequestBuilder<HybridChunkDocumentRequest, HybridChunkDocumentRequestBuilder> { }
}
