package ai.docling.serve.api.chunk.request;

import java.util.Collection;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import ai.docling.serve.api.chunk.request.options.HybridChunkerOptions;
import ai.docling.serve.api.convert.request.source.Source;
import ai.docling.serve.api.convert.request.target.Target;

/**
 * Represents a request to convert a document and chunk it into smaller documents
 * using the Docling hybrid chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@lombok.extern.jackson.Jacksonized
@lombok.experimental.SuperBuilder(toBuilder = true)
@lombok.Getter
@lombok.ToString(callSuper = true)
public final class HybridChunkDocumentRequest extends ChunkDocumentRequest {
  /**
   * Options specific to the chunker.
   *
   * @param chunkingOptions the hybrid chunker options
   * @return the hybrid chunker options
   */
  @JsonProperty("chunking_options")
  @lombok.NonNull
  @lombok.Builder.Default
  private HybridChunkerOptions chunkingOptions = HybridChunkerOptions.builder().build();

  /**
   * Builder for creating {@link HybridChunkDocumentRequest} instances.
   * Generated by Lombok's {@code @SuperBuilder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   * <li>{@code source(Source)} - Add a single document source (use with @Singular)</li>
   * <li>{@code sources(List<Source>)} - Set the list of document sources</li>
   * <li>{@code options(ConvertDocumentOptions)} - Set the conversion options</li>
   * <li>{@code target(Target)} - Set the output target specification</li>
   * <li>{@code includeConvertedDoc(boolean)} - Set whether to include converted document</li>
   * <li>{@code chunkingOptions(HybridChunkerOptions)} - Set the hybrid chunker options</li>
   * </ul>
   */
  public static abstract class HybridChunkDocumentRequestBuilder extends ChunkDocumentRequest.ChunkDocumentRequestBuilder<HybridChunkDocumentRequest, HybridChunkDocumentRequestBuilder> {
  }

  /**
   * Builder for {@link HybridChunkDocumentRequest}.
   *
   * <p>The {@code source}, {@code sources}, {@code clearSources}, and {@code target} mutators are
   * redeclared here (delegating to the base builder) so that they are members of this concrete
   * builder type rather than being inherited only from {@link ChunkDocumentRequest.Builder}. This
   * keeps fluent calls such as {@code HybridChunkDocumentRequest.builder().source(...)} resolvable
   * under GraalVM native image {@code --link-at-build-time}, where a virtual call whose declared
   * owner is this subtype must be found on the subtype itself.
   */
  public abstract static class Builder<C extends HybridChunkDocumentRequest, B extends Builder<C, B>> extends ChunkDocumentRequest.Builder<C, B> {
    @Override
    public B source(Source source) {
      return super.source(source);
    }

    @Override
    public B sources(Collection<? extends Source> sources) {
      return super.sources(sources);
    }

    @Override
    public B clearSources() {
      return super.clearSources();
    }

    @Override
    public B target(Target target) {
      return super.target(target);
    }
  }
}
