package ai.docling.serve.api.task.response;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the response for polling the status of a task.
 *
 * This class encapsulates details about a specific task's current status,
 * including its identifier, type, position in a queue, and metadata regarding
 * its progress and outcomes. The object is serialized and deserialized using
 * Jackson annotations, ensuring compatibility with JSON-based APIs.
 *
 * Features:
 * - Uses a builder pattern with {@code lombok.Builder} for creating immutable objects.
 * - Serialized to JSON only if fields are non-empty.
 * - Metadata field for detailed task status is optional.
 *
 * Fields:
 * - {@code taskId}: The unique identifier for the task.
 * - {@code taskType}: The type of task being processed (optional).
 * - {@code taskStatus}: The current status of the task, as defined in the {@code TaskStatus} enum.
 * - {@code taskPosition}: A numerical representation of the task's position in the processing queue.
 * - {@code taskStatusMetadata}: Metadata providing detailed statistics and progress information (optional).
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = TaskStatusPollResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class TaskStatusPollResponse {
  /**
   * Unique task identifier.
   *
   * @param taskId the task ID
   * @return the task ID
   */
  @JsonProperty("task_id")
  private String taskId;

  /**
   * Type of task (convert or chunk).
   *
   * @param taskType the task type, or null if not specified
   * @return the task type, or null if not specified
   */
  @JsonProperty("task_type")
  @Nullable
  private String taskType;

  /**
   * Current status of the task.
   *
   * @param taskStatus the task status
   * @return the task status
   */
  @JsonProperty("task_status")
  private TaskStatus taskStatus;

  /**
   * Position of task in the processing queue (if queued).
   *
   * @param taskPosition the queue position, or null if not queued
   * @return the queue position, or null if not queued
   */
  @JsonProperty("task_position")
  @Nullable
  private Long taskPosition;

  /**
   * Metadata about task processing progress.
   *
   * @param taskStatusMetadata the task metadata, or null if not available
   * @return the task metadata, or null if not available
   */
  @JsonProperty("task_meta")
  @Nullable
  private TaskStatusMetadata taskStatusMetadata;

  /**
   * Builder for creating {@link TaskStatusPollResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code taskId(String)} - Set the task ID</li>
   *   <li>{@code taskType(String)} - Set the task type</li>
   *   <li>{@code taskStatus(TaskStatus)} - Set the task status</li>
   *   <li>{@code taskPosition(Long)} - Set the queue position</li>
   *   <li>{@code taskStatusMetadata(TaskStatusMetadata)} - Set the task metadata</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
