package ai.docling.serve.api.task.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents metadata for the status of a task, providing detailed information
 * about the task's progress and outcomes.
 *
 * This class is used to encapsulate the statistical data related to the execution
 * of a task, such as the number of documents processed, succeeded, or failed. It
 * is intended for use in tracking task processing and is serialized to JSON for
 * communication between system components.
 *
 * Features:
 * - Serialization and deserialization using Jackson annotations.
 * - All fields are included in the JSON only if they are non-empty.
 * - Immutable structure with a builder pattern for object creation.
 *
 * Fields:
 * - {@code numDocs}: The total number of documents associated with the task.
 * - {@code numProcessed}: The number of documents that have been processed.
 * - {@code numSucceeded}: The number of documents that were successfully processed.
 * - {@code numFailed}: The number of documents that failed processing.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = TaskStatusMetadata.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class TaskStatusMetadata {
  /**
   * Total number of documents in the task.
   *
   * @param numDocs the total number of documents
   * @return the total number of documents
   */
  @JsonProperty("num_docs")
  private Long numDocs;

  /**
   * Number of documents processed so far.
   *
   * @param numProcessed the number of processed documents
   * @return the number of processed documents
   */
  @JsonProperty("num_processed")
  private Long numProcessed;

  /**
   * Number of documents that succeeded.
   *
   * @param numSucceeded the number of successful documents
   * @return the number of successful documents
   */
  @JsonProperty("num_succeeded")
  private Long numSucceeded;

  /**
   * Number of documents that failed.
   *
   * @param numFailed the number of failed documents
   * @return the number of failed documents
   */
  @JsonProperty("num_failed")
  private Long numFailed;

  /**
   * Builder for creating {@link TaskStatusMetadata} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code numDocs(Long)} - Set the total number of documents</li>
   *   <li>{@code numProcessed(Long)} - Set the number of processed documents</li>
   *   <li>{@code numSucceeded(Long)} - Set the number of successful documents</li>
   *   <li>{@code numFailed(Long)} - Set the number of failed documents</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
