package ai.docling.serve.api.task.request;

/**
 * Represents a request to retrieve the result of a task.
 *
 * This class is used to encapsulate the necessary information required to
 * request the result corresponding to the task identified by its unique task ID.
 * Instances of this class are immutable and can be built using the provided
 * builder methods.
 *
 * Attributes:
 * - `taskId`: The unique identifier of the task whose result is being requested.
 *             This field is mandatory and must not be null.
 */
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class TaskResultRequest {
  /**
   * The unique identifier of the task whose result is being requested.
   *
   * @param taskId the task ID
   * @return the task ID
   */
  @lombok.NonNull
  private String taskId;

  /**
   * Builder for creating {@link TaskResultRequest} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code taskId(String)} - Set the task ID</li>
   * </ul>
   */
  public static class TaskResultRequestBuilder { }
}
