package ai.docling.serve.api.convert.response;

import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Response returned by the Convert API for a single conversion request.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections/strings are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ConvertDocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ConvertDocumentResponse {
  /**
   * Converted document content.
   *
   * @param document the converted document
   * @return the converted document
   */
  @JsonProperty("document")
  private DocumentResponse document;

  /**
   * List of errors that occurred during conversion.
   *
   * @param errors the list of errors
   * @return the list of errors
   */
  @JsonProperty("errors")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<ErrorItem> errors;

  /**
   * Total processing time in seconds.
   *
   * @param processingTime the processing time in seconds
   * @return the processing time in seconds
   */
  @JsonProperty("processing_time")
  private Double processingTime;

  /**
   * Conversion status (success, failure, partial_success, etc.).
   *
   * @param status the conversion status
   * @return the conversion status
   */
  @JsonProperty("status")
  private String status;

  /**
   * Detailed timing information for processing stages.
   *
   * @param timings the map of timing information
   * @return the map of timing information
   */
  @JsonProperty("timings")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private Map<String, Object> timings;

  /**
   * Builder for creating {@link ConvertDocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code document(DocumentResponse)} - Set the converted document</li>
   *   <li>{@code error(ErrorItem)} - Add a single error (use with @Singular)</li>
   *   <li>{@code errors(List<ErrorItem>)} - Set the list of errors</li>
   *   <li>{@code processingTime(Double)} - Set the processing time in seconds</li>
   *   <li>{@code status(String)} - Set the conversion status</li>
   *   <li>{@code timing(String, Object)} - Add a single timing entry (use with @Singular)</li>
   *   <li>{@code timings(Map<String, Object>)} - Set the map of timing information</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
