package ai.docling.serve.api.convert.response;

import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Represents the conversion outcome and artifact references for a single source document.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = DocumentArtifactItem.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class DocumentArtifactItem {

  /**
   * Zero-based index of the source document within the originating task.
   *
   * @param sourceIndex the source index
   * @return the source index
   */
  @JsonProperty("source_index")
  private Integer sourceIndex;

  /**
   * Canonical identifier of the source document.
   *
   * @param sourceUri the source URI
   * @return the source URI
   */
  @JsonProperty("source_uri")
  @lombok.NonNull
  private String sourceUri;

  /**
   * Filename used as the stem of each output artifact.
   *
   * @param filename the source filename
   * @return the source filename
   */
  @JsonProperty("filename")
  @lombok.NonNull
  private String filename;

  /**
   * Terminal conversion outcome for this document.
   *
   * @param status the conversion status
   * @return the conversion status
   */
  @JsonProperty("status")
  @lombok.NonNull
  private ConversionStatus status;

  /**
   * Errors encountered while converting this document.
   *
   * @param errors the list of errors
   * @return the list of errors
   */
  @JsonProperty("errors")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<ErrorItem> errors;

  /**
   * Per-stage timing breakdown keyed by stage name.
   *
   * @param timings the timings map
   * @return the timings map
   */
  @JsonProperty("timings")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private Map<String, ProfilingItem> timings;

  /**
   * Presigned URLs for each requested output format.
   *
   * @param artifacts the list of artifact references
   * @return the list of artifact references
   */
  @JsonProperty("artifacts")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<ArtifactRef> artifacts;

  /**
   * Builder for creating {@link DocumentArtifactItem} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code sourceIndex(Integer)} - Set the source index</li>
   *   <li>{@code sourceUri(String)} - Set the source URI</li>
   *   <li>{@code filename(String)} - Set the source filename</li>
   *   <li>{@code status(ConversionStatus)} - Set the conversion status</li>
   *   <li>{@code errors(List<ErrorItem>)} - Set the list of errors</li>
   *   <li>{@code error(ErrorItem)} - Add a single error (use with @Singular)</li>
   *   <li>{@code timings(Map<String, ProfilingItem>)} - Set the timings map</li>
   *   <li>{@code timing(String, ProfilingItem)} - Add a single timing entry (use with @Singular)</li>
   *   <li>{@code artifacts(List<ArtifactRef>)} - Set the list of artifact references</li>
   *   <li>{@code artifact(ArtifactRef)} - Add a single artifact reference (use with @Singular)</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
