package ai.docling.serve.api.convert.response;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import ai.docling.core.DoclingDocument;

/**
 * A simple mutable POJO representing the converted document returned by the
 * Docling Convert API. The properties map 1:1 to the JSON payload using the
 * {@link JsonProperty} names declared on each field.
 *
 * <p>Serialization is configured with {@link JsonInclude.Include#NON_EMPTY},
 * meaning nulls, empty strings, and empty collections/maps are omitted from the
 * serialized JSON.</p>
 *
 * <p>Notes on mutability and maps:</p>
 * <ul>
 *   <li>{@code jsonContent} defaults to an empty map and is never exposed as
 *   {@code null}. The getter returns an unmodifiable view.</li>
 *   <li>When setting {@code jsonContent} with a non-null map, the reference is
 *   preserved; subsequent external modifications to the provided map are
 *   observable via {@link #getJsonContent()}.</li>
 * </ul>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = DocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class DocumentResponse {
  /**
   * Document content in DocTags format (if requested).
   *
   * @param doctagsContent the DocTags content, or null if not requested
   * @return the DocTags content, or null if not requested
   */
  @JsonProperty("doctags_content")
  @Nullable
  private String doctagsContent;

  /**
   * Filename of the source document.
   *
   * @param filename the filename
   * @return the filename
   */
  @JsonProperty("filename")
  private String filename;

  /**
   * Document content in HTML format (if requested).
   *
   * @param htmlContent the HTML content, or null if not requested
   * @return the HTML content, or null if not requested
   */
  @JsonProperty("html_content")
  @Nullable
  private String htmlContent;

  /**
   * Document content as DoclingDocument JSON (if requested).
   *
   * @param jsonContent the JSON content, or null if not requested
   * @return the JSON content, or null if not requested
   */
  @JsonProperty("json_content")
  @Nullable
  private DoclingDocument jsonContent;

  /**
   * Document content in Markdown format (if requested).
   *
   * @param markdownContent the Markdown content, or null if not requested
   * @return the Markdown content, or null if not requested
   */
  @JsonProperty("md_content")
  @Nullable
  private String markdownContent;

  /**
   * Document content as plain text (if requested).
   *
   * @param textContent the text content, or null if not requested
   * @return the text content, or null if not requested
   */
  @JsonProperty("text_content")
  @Nullable
  private String textContent;

  /**
   * Builder for creating {@link DocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code doctagsContent(String)} - Set the DocTags content</li>
   *   <li>{@code filename(String)} - Set the filename</li>
   *   <li>{@code htmlContent(String)} - Set the HTML content</li>
   *   <li>{@code jsonContent(DoclingDocument)} - Set the JSON content</li>
   *   <li>{@code markdownContent(String)} - Set the Markdown content</li>
   *   <li>{@code textContent(String)} - Set the text content</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
