package ai.docling.serve.api.convert.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents an individual error produced during document conversion.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * strings are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ErrorItem.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ErrorItem {
  /**
   * Type of Docling component that encountered the error.
   *
   * @param componentType the component type
   * @return the component type
   */
  @JsonProperty("component_type")
  private String componentType;

  /**
   * Error message describing what went wrong.
   *
   * @param errorMessage the error message
   * @return the error message
   */
  @JsonProperty("error_message")
  private String errorMessage;

  /**
   * Name of the module where the error occurred.
   *
   * @param moduleName the module name
   * @return the module name
   */
  @JsonProperty("module_name")
  private String moduleName;

  /**
   * Builder for creating {@link ErrorItem} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code componentType(String)} - Set the component type</li>
   *   <li>{@code errorMessage(String)} - Set the error message</li>
   *   <li>{@code moduleName(String)} - Set the module name</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
