package ai.docling.serve.api.convert.response;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Response for document conversions that target server-managed presigned URLs.
 *
 * <p>This response type is returned when the conversion request specifies a
 * {@link ai.docling.serve.api.convert.request.target.PresignedUrlTarget}. Each
 * source document is represented by a {@link DocumentArtifactItem} in
 * {@link #getDocuments() documents} which carries its conversion outcome and
 * the list of presigned URLs the server produced for the requested output
 * formats.</p>
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections/strings are omitted from JSON output.</p>
 *
 * @see ConvertDocumentResponse
 * @see ResponseType#PRE_SIGNED_URL_RESPONSE
 * @see ai.docling.serve.api.convert.request.target.PresignedUrlTarget
 * @see DocumentArtifactItem
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = PreSignedUrlConvertResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class PreSignedUrlConvertResponse extends ConvertDocumentResponse {

  /**
   * Total processing time in seconds.
   *
   * @param processingTime the processing time in seconds
   * @return the processing time in seconds
   */
  @JsonProperty("processing_time")
  private Double processingTime;

  /**
   * Number of attempted conversions.
   *
   * @param numConverted the number of attempted conversions
   * @return the number of attempted conversions
   */
  @JsonProperty("num_converted")
  private Integer numConverted;

  /**
   * Number of successful conversions.
   *
   * @param numSucceeded the number of successful conversions
   * @return the number of successful conversions
   */
  @JsonProperty("num_succeeded")
  private Integer numSucceeded;

  /**
   * Number of partial successes.
   *
   * @param numPartiallySucceeded the number of partial successes
   * @return the number of partial successes
   */
  @JsonProperty("num_partially_succeeded")
  private Integer numPartiallySucceeded;

  /**
   * Number of failed conversions.
   *
   * @param numFailed the number of failed conversions
   * @return the number of failed conversions
   */
  @JsonProperty("num_failed")
  private Integer numFailed;

  /**
   * Per-source conversion outcomes and presigned artifact URLs.
   *
   * @param documents the list of per-source artifact items
   * @return the list of per-source artifact items
   */
  @JsonProperty("documents")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<DocumentArtifactItem> documents;

  @Override
  @lombok.ToString.Include
  public ResponseType getResponseType() {
    return ResponseType.PRE_SIGNED_URL_RESPONSE;
  }

  /**
   * Builder for creating {@link PreSignedUrlConvertResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code processingTime(Double)} - Set the total processing time in seconds</li>
   *   <li>{@code numConverted(Integer)} - Set the number of attempted conversions</li>
   *   <li>{@code numSucceeded(Integer)} - Set the number of successful conversions</li>
   *   <li>{@code numPartiallySucceeded(Integer)} - Set the number of partial successes</li>
   *   <li>{@code numFailed(Integer)} - Set the number of failed conversions</li>
   *   <li>{@code documents(List<DocumentArtifactItem>)} - Set the list of per-source artifact items</li>
   *   <li>{@code document(DocumentArtifactItem)} - Add a single per-source artifact item (use with @Singular)</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
