package ai.docling.serve.api.convert.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response for document conversions with S3 or PUT target types.
 *
 * <p>This response type is returned when the conversion request specifies
 * an S3 target or PUT target. The converted documents are stored in the
 * specified location.
 * The response includes processing statistics and conversion metrics.</p>
 *
 * <p>This response type is returned in any one the following scenarios:</p>
 * <ul>
 *   <li>Target type is {@link ai.docling.serve.api.convert.request.target.PutTarget}</li>
 *   <li>Target type is {@link ai.docling.serve.api.convert.request.target.S3Target}</li>
 * </ul>
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections/strings are omitted from JSON output.</p>
 *
 * @see ConvertDocumentResponse
 * @see ResponseType#PRE_SIGNED_URL
 * @see ai.docling.serve.api.convert.request.target.S3Target
 * @see ai.docling.serve.api.convert.request.target.PutTarget
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = PreSignedUrlConvertDocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class PreSignedUrlConvertDocumentResponse extends ConvertDocumentResponse {

  /**
   * Total processing time in seconds.
   *
   * @param processingTime the processing time in seconds
   * @return the processing time in seconds
   */
  @JsonProperty("processing_time")
  private Double processingTime;

  /**
   * Number of attempted conversions
   *
   * @param num_converted the number of attempted conversions
   * @return the number of attempted conversions
   */
  @JsonProperty("num_converted")
  private Integer numConverted;

  /**
   * Number of successful conversions
   *
   * @param numSucceeded the number of successful conversions
   * @return the number of successful conversions
   */
  @JsonProperty("num_succeeded")
  private Integer numSucceeded;

  /**
   * Number of failed conversions
   *
   * @param numFailed the number of failed conversions
   * @return the number of failed conversions
   */
  @JsonProperty("num_failed")
  private Integer numFailed;

  @Override
  @lombok.ToString.Include
  public ResponseType getResponseType() {
    return ResponseType.PRE_SIGNED_URL;
  }

  /**
   * Builder for creating {@link PreSignedUrlConvertDocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code processingTime(Double)} - Set the total processing time in seconds</li>
   *   <li>{@code numConverted(Integer)} - Set the number of attempted conversions</li>
   *   <li>{@code numSucceeded(Integer)} - Set the number of successful conversions</li>
   *   <li>{@code numFailed(Integer)} - Set the number of failed conversions</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
