package ai.docling.serve.api.convert.response;

import java.time.Instant;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import ai.docling.serve.api.serialization.Jackson2InstantDeserializer;
import ai.docling.serve.api.serialization.Jackson2InstantSerializer;
import ai.docling.serve.api.serialization.Jackson3InstantDeserializer;
import ai.docling.serve.api.serialization.Jackson3InstantSerializer;

/**
 * Represents per-stage timing measurements produced during a document conversion.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ProfilingItem.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ProfilingItem {

  /**
   * Scope of the stage being measured.
   *
   * @param scope the profiling scope
   * @return the profiling scope
   */
  @JsonProperty("scope")
  private ProfilingScope scope;

  /**
   * Number of measurements recorded.
   *
   * @param count the measurement count
   * @return the measurement count
   */
  @JsonProperty("count")
  private Integer count;

  /**
   * Per-measurement durations in seconds.
   *
   * @param times the list of durations
   * @return the list of durations
   */
  @JsonProperty("times")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Double> times;

  /**
   * Start timestamps for each measurement.
   *
   * @param startTimestamps the list of start timestamps
   * @return the list of start timestamps
   */
  @JsonProperty("start_timestamps")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @JsonSerialize(contentUsing = Jackson2InstantSerializer.class)
  @JsonDeserialize(contentUsing = Jackson2InstantDeserializer.class)
  @tools.jackson.databind.annotation.JsonSerialize(contentUsing = Jackson3InstantSerializer.class)
  @tools.jackson.databind.annotation.JsonDeserialize(contentUsing = Jackson3InstantDeserializer.class)
  @lombok.Singular
  private List<Instant> startTimestamps;

  /**
   * Builder for creating {@link ProfilingItem} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code scope(ProfilingScope)} - Set the profiling scope</li>
   *   <li>{@code count(Integer)} - Set the measurement count</li>
   *   <li>{@code times(List<Double>)} - Set the list of durations</li>
   *   <li>{@code time(Double)} - Add a single duration (use with @Singular)</li>
   *   <li>{@code startTimestamps(List<Instant>)} - Set the list of start timestamps</li>
   *   <li>{@code startTimestamp(Instant)} - Add a single start timestamp (use with @Singular)</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
