package ai.docling.serve.api.convert.response;

import java.io.InputStream;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response for document conversions delivered as a ZIP archive.
 *
 * <p>This response type is returned in any one the following scenarios:</p>
 * <ul>
 *   <li>The conversion request contains multiple source files with {@link ai.docling.serve.api.convert.request.target.InBodyTarget}/li>
 *   <li>The target type is {@link ai.docling.serve.api.convert.request.target.ZipTarget}</li>
 * </ul>
 *
 * <p>The response includes the ZIP file name and an input stream to read
 * the archive contents. All converted documents and their associated assets
 * are packaged together in the ZIP file.</p>
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections/strings are omitted from JSON output.</p>
 *
 * @see ConvertDocumentResponse
 * @see ResponseType#ZIP_ARCHIVE
 * @see ai.docling.serve.api.convert.request.target.ZipTarget
 * @see ai.docling.serve.api.convert.request.ConvertDocumentRequest
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ZipArchiveConvertDocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class ZipArchiveConvertDocumentResponse extends ConvertDocumentResponse {

  /**
   * Name of the ZIP archive file containing the converted documents.
   *
   * <p>This is the suggested filename for saving the ZIP archive locally.</p>
   *
   * @param fileName the ZIP archive file name
   * @return the ZIP archive file name
   */

  @JsonProperty("file_name")
  @lombok.Builder.Default
  private String fileName = "converted_docs.zip";

  /**
   * Input stream for reading the ZIP archive contents.
   *
   * <p>This stream provides access to the binary ZIP file data containing
   * all converted documents and their assets. The stream should be properly
   * closed after reading to release resources.</p>
   *
   * <p><strong>Note:</strong> This field is typically not serialized to JSON
   * as it represents binary data. It's used for programmatic access to the
   * ZIP archive contents.</p>
   *
   * @param inputStream the input stream for the ZIP archive
   * @return the input stream for the ZIP archive
   */
  @JsonIgnore
  private InputStream inputStream;

  @Override
  @lombok.ToString.Include
  public ResponseType getResponseType() {
    return ResponseType.ZIP_ARCHIVE;
  }

  /**
   * Builder for creating {@link ZipArchiveConvertDocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:</p>
   * <ul>
   *   <li>{@code fileName(String)} - Set the ZIP archive file name</li>
   *   <li>{@code inputStream(InputStream)} - Set the input stream for the ZIP archive</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
