package ai.docling.serve.api.convert.request.source;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a file-based data source.
 * This class provides functionality to handle Base64-encoded file content and filenames
 * for file sources. Inherits from {@link Source}.
 *
 * <p>JSON serialization/deserialization:
 * <ul>
 *   <li>{@code base64_string} - Represents the Base64-encoded content of the file.</li>
 *   <li>{@code filename} - Represents the name of the uploaded file.</li>
 * </ul>
 *
 * <p>By default, JSON includes non-empty fields only.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = FileSource.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class FileSource extends Source {
  /**
   * Content of the file serialized in base64. For example it can be obtained via `base64 -w 0 /path/to/file/pdf-to-convert.pdf`.
   *
   * @param base64String the base64-encoded file content
   * @return the base64-encoded file content
   */
  @JsonProperty("base64_string")
  @lombok.NonNull
  private String base64String;

  /**
   * Filename of the uploaded document.
   *
   * @param filename the filename
   * @return the filename
   */
  @JsonProperty("filename")
  @lombok.NonNull
  private String filename;

  /**
   * Builder for creating {@link FileSource} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code base64String(String)} - Set the base64-encoded file content</li>
   *   <li>{@code filename(String)} - Set the filename</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
