package ai.docling.serve.api.chunk.response;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Response returned by the Chunk API for a single conversion request.
 *
 * <p>Serialization uses {@link JsonInclude.Include#NON_EMPTY}, so nulls and empty
 * collections/strings are omitted from JSON output.</p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ChunkDocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ChunkDocumentResponse {

  /**
   * List of document chunks.
   *
   * @param chunks the list of chunks
   * @return the list of chunks
   */
  @JsonProperty("chunks")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Chunk> chunks;

  /**
   * List of converted documents (if include_converted_doc was true).
   *
   * @param documents the list of converted documents
   * @return the list of converted documents
   */
  @JsonProperty("documents")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Document> documents;

  /**
   * Total processing time in seconds.
   *
   * @param processingTime the processing time in seconds
   * @return the processing time in seconds
   */
  @JsonProperty("processing_time")
  private Double processingTime;

  /**
   * Builder for creating {@link ChunkDocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code chunk(Chunk)} - Add a single chunk (use with @Singular)</li>
   *   <li>{@code chunks(List<Chunk>)} - Set the list of chunks</li>
   *   <li>{@code document(Document)} - Add a single document (use with @Singular)</li>
   *   <li>{@code documents(List<Document>)} - Set the list of converted documents</li>
   *   <li>{@code processingTime(Double)} - Set the processing time in seconds</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
