package ai.docling.serve.api.chunk.response;

import java.util.List;
import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Represents a chunk of a document after it has been processed by a Docling chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = Chunk.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class Chunk {

  /**
   * Filename of the source document.
   *
   * @param filename the filename of the source document
   * @return the filename of the source document
   */
  @JsonProperty("filename")
  private String filename;

  /**
   * Index of this chunk within the document.
   *
   * @param chunkIndex the zero-based chunk index
   * @return the zero-based chunk index
   */
  @JsonProperty("chunk_index")
  private int chunkIndex;

  /**
   * The chunk text with structural context (headers, formatting).
   *
   * @param text the formatted chunk text
   * @return the formatted chunk text
   */
  @JsonProperty("text")
  private String text;

  /**
   * Raw chunk text without additional formatting or context.
   *
   * @param rawText the raw chunk text, or null if not included
   * @return the raw chunk text, or null if not included
   */
  @JsonProperty("raw_text")
  @Nullable
  private String rawText;

  /**
   * Number of tokens in the text, if the chunker is aware of tokens.
   *
   * @param numTokens the number of tokens, or null if not calculated
   * @return the number of tokens, or null if not calculated
   */
  @JsonProperty("num_tokens")
  private Integer numTokens;

  /**
   * List of headings for this chunk.
   *
   * @param headings the list of headings
   * @return the list of headings
   */
  @JsonProperty("headings")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<String> headings;

  /**
   * List of captions for this chunk (e.g. for pictures and tables).
   *
   * @param captions the list of captions
   * @return the list of captions
   */
  @JsonProperty("captions")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<String> captions;

  /**
   * List of doc items references.
   *
   * @param docItems the list of document item references
   * @return the list of document item references
   */
  @JsonProperty("doc_items")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<String> docItems;

  /**
   * Page numbers where this chunk content appears.
   *
   * @param pageNumbers the list of page numbers
   * @return the list of page numbers
   */
  @JsonProperty("page_numbers")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Integer> pageNumbers;

  /**
   * Additional metadata associated with this chunk.
   *
   * @param metadata the metadata map
   * @return the metadata map
   */
  @JsonProperty("metadata")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular("metadata")
  private Map<String, Object> metadata;

  /**
   * Builder for creating {@link Chunk} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code filename(String)} - Set the filename of the source document</li>
   *   <li>{@code chunkIndex(int)} - Set the zero-based chunk index</li>
   *   <li>{@code text(String)} - Set the formatted chunk text</li>
   *   <li>{@code rawText(String)} - Set the raw chunk text</li>
   *   <li>{@code numTokens(Integer)} - Set the number of tokens</li>
   *   <li>{@code heading(String)} - Add a single heading (use with @Singular)</li>
   *   <li>{@code headings(List<String>)} - Set the list of headings</li>
   *   <li>{@code caption(String)} - Add a single caption (use with @Singular)</li>
   *   <li>{@code captions(List<String>)} - Set the list of captions</li>
   *   <li>{@code docItem(String)} - Add a single doc item reference (use with @Singular)</li>
   *   <li>{@code docItems(List<String>)} - Set the list of doc items</li>
   *   <li>{@code pageNumber(Integer)} - Add a single page number (use with @Singular)</li>
   *   <li>{@code pageNumbers(List<Integer>)} - Set the list of page numbers</li>
   *   <li>{@code metadata(String, Object)} - Add a single metadata entry (use with @Singular)</li>
   *   <li>{@code metadata(Map<String, Object>)} - Set the metadata map</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
