package ai.docling.serve.api.chunk.response;

import java.util.List;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

import ai.docling.serve.api.convert.response.ErrorItem;

/**
 * Represents the document being processed by a Docling chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = Document.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class Document {

  /**
   * The type or kind of document.
   * This may indicate the document format or processing pipeline used.
   *
   * @param kind the document kind, or null if not specified
   * @return the document kind, or null if not specified
   */
  @JsonProperty("kind")
  @Nullable
  private String kind;

  /**
   * The converted document content in various export formats.
   * Contains the document data before chunking was applied.
   *
   * @param content the exported document content
   * @return the exported document content
   */
  @JsonProperty("content")
  private ExportDocumentResponse content;

  /**
   * Processing status of the document.
   * Common values include "success", "failure", or "partial".
   *
   * @param status the processing status
   * @return the processing status
   */
  @JsonProperty("status")
  private String status;

  /**
   * List of errors that occurred during document processing.
   * Empty if the document was processed without errors.
   *
   * @param errors the list of errors
   * @return the list of errors
   */
  @JsonProperty("errors")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<ErrorItem> errors;

  /**
   * Builder for creating {@link Document} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code kind(String)} - Set the document kind</li>
   *   <li>{@code content(ExportDocumentResponse)} - Set the exported document content</li>
   *   <li>{@code status(String)} - Set the processing status</li>
   *   <li>{@code error(ErrorItem)} - Add a single error (use with @Singular)</li>
   *   <li>{@code errors(List<ErrorItem>)} - Set the list of errors</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
