package ai.docling.serve.api.chunk.response;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import ai.docling.core.DoclingDocument;

/**
 * Content of the original converted document, before getting chunked.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ExportDocumentResponse.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ExportDocumentResponse {

  /**
   * The name of the original document file.
   *
   * @param filename the filename
   * @return the filename
   */
  @JsonProperty("filename")
  private String filename;

  /**
   * The document content exported in Markdown format.
   * Present if Markdown output was requested in the conversion options.
   *
   * @param markdownContent the Markdown content, or null if not requested
   * @return the Markdown content, or null if not requested
   */
  @JsonProperty("md_content")
  @Nullable
  private String markdownContent;

  /**
   * The document content as a structured DoclingDocument JSON object.
   * Present if JSON output was requested in the conversion options.
   *
   * @param jsonContent the JSON content, or null if not requested
   * @return the JSON content, or null if not requested
   */
  @JsonProperty("json_content")
  @Nullable
  private DoclingDocument jsonContent;

  /**
   * The document content exported in HTML format.
   * Present if HTML output was requested in the conversion options.
   *
   * @param htmlContent the HTML content, or null if not requested
   * @return the HTML content, or null if not requested
   */
  @JsonProperty("html_content")
  @Nullable
  private String htmlContent;

  /**
   * The document content as plain text.
   * Present if text output was requested in the conversion options.
   *
   * @param textContent the text content, or null if not requested
   * @return the text content, or null if not requested
   */
  @JsonProperty("text_content")
  @Nullable
  private String textContent;

  /**
   * The document content in DocTags format.
   * Present if DocTags output was requested in the conversion options.
   *
   * @param doctagsContent the DocTags content, or null if not requested
   * @return the DocTags content, or null if not requested
   */
  @JsonProperty("doctags_content")
  @Nullable
  private String doctagsContent;

  /**
   * Builder for creating {@link ExportDocumentResponse} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code filename(String)} - Set the filename</li>
   *   <li>{@code markdownContent(String)} - Set the Markdown content</li>
   *   <li>{@code jsonContent(DoclingDocument)} - Set the JSON content</li>
   *   <li>{@code htmlContent(String)} - Set the HTML content</li>
   *   <li>{@code textContent(String)} - Set the text content</li>
   *   <li>{@code doctagsContent(String)} - Set the DocTags content</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
