package ai.docling.api.serve.convert.request.options;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Type of response generated by the model.
 */
public enum ResponseFormat {

  @JsonProperty("doctags") DOCTAGS,
  @JsonProperty("markdown") MARKDOWN,
  @JsonProperty("html") HTML,
  @JsonProperty("otsl") OTSL,
  @JsonProperty("plaintext") PLAINTEXT

}
