package ai.docling.serve.api.chunk.request.options;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Options for configuring the hierarchical chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = HierarchicalChunkerOptions.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class HierarchicalChunkerOptions extends ChunkerOptions {

  /**
   * Use markdown table format instead of triplets for table serialization.
   *
   * @param useMarkdownTables true if markdown tables should be used, false otherwise
   * @return true if markdown tables should be used, false otherwise
   */
  @JsonProperty("use_markdown_tables")
  private boolean useMarkdownTables;

  /**
   * Include both raw_text and text (contextualized) in response. If False, only text is included.
   *
   * @param includeRawText true if raw text should be included, false otherwise
   * @return true if raw text should be included, false otherwise
   */
  @JsonProperty("include_raw_text")
  private boolean includeRawText;

  /**
   * Builder for creating {@link HierarchicalChunkerOptions} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code useMarkdownTables(boolean)} - Set whether to use markdown table format</li>
   *   <li>{@code includeRawText(boolean)} - Set whether to include raw text in response</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
