package ai.docling.serve.api.chunk.request.options;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Options for configuring the hybrid chunker.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = HybridChunkerOptions.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public final class HybridChunkerOptions extends ChunkerOptions {

  /**
   * Use markdown table format instead of triplets for table serialization.
   *
   * @param useMarkdownTables true if markdown tables should be used, false otherwise
   * @return true if markdown tables should be used, false otherwise
   */
  @JsonProperty("use_markdown_tables")
  private boolean useMarkdownTables;

  /**
   * Include both raw_text and text (contextualized) in response. If False, only text is included.
   *
   * @param includeRawText true if raw text should be included, false otherwise
   * @return true if raw text should be included, false otherwise
   */
  @JsonProperty("include_raw_text")
  private boolean includeRawText;

  /**
   * Maximum number of tokens per chunk. When left to none, the value is automatically extracted from the tokenizer.
   *
   * @param maxTokens the maximum number of tokens per chunk, or null if not specified
   * @return the maximum number of tokens per chunk, or null if not specified
   */
  @JsonProperty("max_tokens")
  @Nullable
  private Integer maxTokens;

  /**
   * HuggingFace model name for custom tokenization. If not specified, uses 'sentence-transformers/all-MiniLM-L6-v2' as default.
   *
   * @param tokenizer the tokenizer model name, or null to use the default
   * @return the tokenizer model name, or null to use the default
   */
  @JsonProperty("tokenizer")
  @Nullable
  private String tokenizer;

  /**
   * Merge undersized successive chunks with same headings.
   *
   * @param mergePeers true if chunks should be merged, false otherwise, or null if not specified
   * @return true if chunks should be merged, false otherwise, or null if not specified
   */
  @JsonProperty("merge_peers")
  private Boolean mergePeers;

  /**
   * Builder for creating {@link HybridChunkerOptions} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code useMarkdownTables(boolean)} - Set whether to use markdown table format</li>
   *   <li>{@code includeRawText(boolean)} - Set whether to include raw text in response</li>
   *   <li>{@code maxTokens(Integer)} - Set the maximum number of tokens per chunk</li>
   *   <li>{@code tokenizer(String)} - Set the HuggingFace model name for tokenization</li>
   *   <li>{@code mergePeers(Boolean)} - Set whether to merge undersized successive chunks</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }

}
