package ai.docling.serve.api.convert.request;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

import ai.docling.serve.api.convert.request.options.ConvertDocumentOptions;
import ai.docling.serve.api.convert.request.source.Source;
import ai.docling.serve.api.convert.request.target.Target;

/**
 * Represents a request to batch convert document sources. The batch endpoint processes multiple
 * documents asynchronously and returns a task ID for tracking progress. Sources can be HTTP URLs
 * or S3 buckets, and results are delivered to a presigned URL or S3 target.
 *
 * <p>This class is serialized into JSON to conform to the API specification using
 * {@link JsonProperty} annotations. Fields with {@code null} values or empty collections
 * are omitted from the serialized JSON using {@link JsonInclude}.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = BatchConvertDocumentRequest.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class BatchConvertDocumentRequest {
  /**
   * List of document sources to be converted.
   * Each source can be an HTTP URL or S3 reference.
   *
   * @param sources the list of document sources
   * @return the list of document sources
   */
  @JsonProperty("sources")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Source> sources;

  /**
   * Target specification for where the converted documents should be delivered.
   * Must be either a {@link ai.docling.serve.api.convert.request.target.PresignedUrlTarget}
   * or {@link ai.docling.serve.api.convert.request.target.S3Target}.
   *
   * @param target the output target
   * @return the output target
   */
  @JsonProperty("target")
  @lombok.NonNull
  private Target target;

  /**
   * Options controlling the document conversion process.
   * Includes settings for OCR, output formats, processing pipelines, and more.
   *
   * @param options the conversion options
   * @return the conversion options
   */
  @JsonProperty("options")
  @lombok.NonNull
  @lombok.Builder.Default
  private ConvertDocumentOptions options = ConvertDocumentOptions.builder().build();

  /**
   * Webhook callbacks for receiving progress notifications during batch processing.
   *
   * @param callbacks the list of callback specifications
   * @return the list of callback specifications
   */
  @JsonProperty("callbacks")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<CallbackSpec> callbacks;

  /**
   * Builder for creating {@link BatchConvertDocumentRequest} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   *
   * <p>Builder methods:
   * <ul>
   *   <li>{@code source(Source)} - Add a single document source</li>
   *   <li>{@code sources(List<Source>)} - Set the list of document sources</li>
   *   <li>{@code target(Target)} - Set the output target</li>
   *   <li>{@code options(ConvertDocumentOptions)} - Set the conversion options</li>
   *   <li>{@code callback(CallbackSpec)} - Add a single callback specification</li>
   *   <li>{@code callbacks(List<CallbackSpec>)} - Set the list of callback specifications</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
