package ai.docling.serve.api.convert.request;

import java.util.List;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

import ai.docling.serve.api.convert.request.options.ConvertDocumentOptions;
import ai.docling.serve.api.convert.request.source.Source;
import ai.docling.serve.api.convert.request.target.Target;

/**
 * Represents a request to convert a document. The request includes the source(s) of the document,
 * options for the conversion process, and the target specification for the converted output.
 *
 * <p>This class is serialized into JSON to conform to the API specification using
 * {@link JsonProperty} annotations. Fields with {@code null} values or empty collections
 * are omitted from the serialized JSON using {@link JsonInclude}.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = ConvertDocumentRequest.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class ConvertDocumentRequest {
  /**
   * List of document sources to be converted.
   * Each source can be a file (base64-encoded) or an HTTP URL.
   *
   * @param sources the list of document sources
   * @return the list of document sources
   */
  @JsonProperty("sources")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular
  private List<Source> sources;

  /**
   * Options controlling the document conversion process.
   * Includes settings for OCR, output formats, processing pipelines, and more.
   *
   * @param options the conversion options
   * @return the conversion options
   */
  @JsonProperty("options")
  @lombok.NonNull
  @lombok.Builder.Default
  private ConvertDocumentOptions options = ConvertDocumentOptions.builder().build();

  /**
   * Target specification for where the converted document should be delivered.
   * If not specified, the result is returned in the response body.
   *
   * @param target the output target, or null if not specified
   * @return the output target, or null if not specified
   */
  @JsonProperty("target")
  @Nullable
  private Target target;

  /**
   * Builder for creating {@link ConvertDocumentRequest} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code source(Source)} - Add a single document source (use with @Singular)</li>
   *   <li>{@code sources(List<Source>)} - Set the list of document sources</li>
   *   <li>{@code options(ConvertDocumentOptions)} - Set the conversion options</li>
   *   <li>{@code target(Target)} - Set the output target</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
