package ai.docling.serve.api.convert.request.options;

import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Configuration for local picture description generation.
 * This class contains settings for generating descriptions of pictures using a local model.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = PictureDescriptionLocal.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class PictureDescriptionLocal {
  /**
   * Repository id from the Hugging Face Hub.
   *
   * @param repoId the Hugging Face repository ID
   * @return the Hugging Face repository ID
   */
  @JsonProperty("repo_id")
  @lombok.NonNull
  private String repoId;

  /**
   * Prompt used when calling the vision-language model.
   *
   * @param prompt the prompt text, or null if not specified
   * @return the prompt text, or null if not specified
   */
  @JsonProperty("prompt")
  @Nullable
  private String prompt;

  /**
   * Config from https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig
   *
   * @param generationConfig the generation configuration map
   * @return the generation configuration map
   */
  @JsonProperty("generation_config")
  @JsonSetter(nulls = Nulls.AS_EMPTY)
  @lombok.Singular("generationConfig")
  private Map<String, Object> generationConfig;

  /**
   * Builder for creating {@link PictureDescriptionLocal} instances.
   * Generated by Lombok's {@code @Builder} annotation.
   * 
   * <p>Builder methods:
   * <ul>
   *   <li>{@code repoId(String)} - Set the Hugging Face repository ID</li>
   *   <li>{@code prompt(String)} - Set the prompt text</li>
   *   <li>{@code generationConfig(String, Object)} - Add a single config entry (use with @Singular)</li>
   *   <li>{@code generationConfig(Map<String, Object>)} - Set the generation configuration map</li>
   * </ul>
   */
  @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
  public static class Builder { }
}
