package ai.docling.serve.api.convert.request.options;

import java.net.URI;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import ai.docling.serve.api.serialization.DurationSerializationFormat;
import ai.docling.serve.api.serialization.Jackson2DurationSerializer;
import ai.docling.serve.api.serialization.Jackson3DurationSerializer;

/**
 * API details for using a vision-language model for the VLM pipeline.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = VlmModelApi.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class VlmModelApi {
        /**
         * Endpoint which accepts openai-api compatible requests.
         *
         * @param url the API endpoint URL, or null if not specified
         * @return the API endpoint URL, or null if not specified
         */
        @JsonProperty("url")
        @Nullable
        private URI url;

        /**
         * Headers used for calling the API endpoint. For example, it could include authentication headers.
         *
         * @param headers the map of HTTP headers
         * @return the map of HTTP headers
         */
        @JsonProperty("headers")
        @JsonSetter(nulls = Nulls.AS_EMPTY)
        @lombok.Singular
        private Map<String, Object> headers;

        /**
         * Model parameters.
         *
         * @param params the map of model parameters
         * @return the map of model parameters
         */
        @JsonProperty("params")
        @JsonSetter(nulls = Nulls.AS_EMPTY)
        @lombok.Singular
        private Map<String, Object> params;

        /**
         * Timeout for the API request.
         *
         * @param timeout the timeout duration, or null if not specified
         * @return the timeout duration, or null if not specified
         */
        @JsonProperty("timeout")
        @JsonSerialize(using = Jackson2DurationSerializer.class)
        @tools.jackson.databind.annotation.JsonSerialize(using = Jackson3DurationSerializer.class)
        @DurationSerializationFormat(ChronoUnit.SECONDS)
        @Nullable
        private Duration timeout;

        /**
         * Maximum number of concurrent requests to the API.
         *
         * @param concurrency the maximum concurrency, or null if not specified
         * @return the maximum concurrency, or null if not specified
         */
        @JsonProperty("concurrency")
        @Nullable
        private Integer concurrency;

        /**
         * Prompt used when calling the vision-language model.
         *
         * @param prompt the prompt text, or null if not specified
         * @return the prompt text, or null if not specified
         */
        @JsonProperty("prompt")
        @Nullable
        private String prompt;

        /**
         * Scale factor of the images used.
         *
         * @param scale the image scale factor, or null if not specified
         * @return the image scale factor, or null if not specified
         */
        @JsonProperty("scale")
        @Nullable
        private Integer scale;

        /**
         * Type of response generated by the model.
         *
         * @param responseFormat the response format, or null if not specified
         * @return the response format, or null if not specified
         */
        @JsonProperty("response_format")
        @Nullable
        private ResponseFormat responseFormat;

        /**
         * Builder for creating {@link VlmModelApi} instances.
         * Generated by Lombok's {@code @Builder} annotation.
     * 
     * <p>Builder methods:
     * <ul>
     *   <li>{@code url(URI)} - Set the API endpoint URL</li>
     *   <li>{@code header(String, Object)} - Add a single HTTP header (use with @Singular)</li>
     *   <li>{@code headers(Map<String, Object>)} - Set the map of HTTP headers</li>
     *   <li>{@code param(String, Object)} - Add a single parameter (use with @Singular)</li>
     *   <li>{@code params(Map<String, Object>)} - Set the map of model parameters</li>
     *   <li>{@code timeout(Duration)} - Set the timeout duration</li>
     *   <li>{@code concurrency(Integer)} - Set the maximum concurrency</li>
     *   <li>{@code prompt(String)} - Set the prompt text</li>
     *   <li>{@code scale(Integer)} - Set the image scale factor</li>
     *   <li>{@code responseFormat(ResponseFormat)} - Set the response format</li>
     * </ul>
         */
    @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
    public static class Builder { }
}
