package ai.docling.serve.api.convert.request.options;

import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;

/**
 * Options for running a local vision-language model for the VLM pipeline.
 * The parameters refer to a model hosted on Hugging Face.
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@tools.jackson.databind.annotation.JsonDeserialize(builder = VlmModelLocal.Builder.class)
@lombok.extern.jackson.Jacksonized
@lombok.Builder(toBuilder = true)
@lombok.Getter
@lombok.ToString
public class VlmModelLocal {
    /**
     * Repository id from the Hugging Face Hub.
     *
     * @param repoId the Hugging Face repository ID, or null if not specified
     * @return the Hugging Face repository ID, or null if not specified
     */
    @JsonProperty("repo_id")
    @Nullable
    private String repoId;

    /**
     * Prompt used when calling the vision-language model.
     *
     * @param prompt the prompt text, or null if not specified
     * @return the prompt text, or null if not specified
     */
    @JsonProperty("prompt")
    @Nullable
    private String prompt;

    /**
     * Scale factor of the images used.
     *
     * @param scale the image scale factor, or null if not specified
     * @return the image scale factor, or null if not specified
     */
    @JsonProperty("scale")
    @Nullable
    private Integer scale;

    /**
     * Type of response generated by the model.
     *
     * @param responseFormat the response format, or null if not specified
     * @return the response format, or null if not specified
     */
    @JsonProperty("response_format")
    @Nullable
    private ResponseFormat responseFormat;

    /**
     * Inference framework to use.
     *
     * @param inferenceFramework the inference framework, or null if not specified
     * @return the inference framework, or null if not specified
     */
    @JsonProperty("inference_framework")
    @Nullable
    private InferenceFramework inferenceFramework;

    /**
     * Type of transformers auto-model to use.
     *
     * @param transformersModelType the transformers model type, or null if not specified
     * @return the transformers model type, or null if not specified
     */
    @JsonProperty("transformers_model_type")
    @Nullable
    private TransformersModelType transformersModelType;

    /**
     * Config from https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig
     *
     * @param extraGenerationConfig the extra generation configuration map
     * @return the extra generation configuration map
     */
    @JsonProperty("extra_generation_config")
    @JsonSetter(nulls = Nulls.AS_EMPTY)
    @lombok.Singular("extraGenerationConfig")
    private Map<String, Object> extraGenerationConfig;

    /**
     * Builder for creating {@link VlmModelLocal} instances.
     * Generated by Lombok's {@code @Builder} annotation.
     * 
     * <p>Builder methods:
     * <ul>
     *   <li>{@code repoId(String)} - Set the Hugging Face repository ID</li>
     *   <li>{@code prompt(String)} - Set the prompt text</li>
     *   <li>{@code scale(Integer)} - Set the image scale factor</li>
     *   <li>{@code responseFormat(ResponseFormat)} - Set the response format</li>
     *   <li>{@code inferenceFramework(InferenceFramework)} - Set the inference framework</li>
     *   <li>{@code transformersModelType(TransformersModelType)} - Set the transformers model type</li>
     *   <li>{@code extraGenerationConfig(String, Object)} - Add a single config entry (use with @Singular)</li>
     *   <li>{@code extraGenerationConfig(Map<String, Object>)} - Set the generation configuration map</li>
     * </ul>
     */
    @tools.jackson.databind.annotation.JsonPOJOBuilder(withPrefix = "")
    public static class Builder { }

    /**
     * Inference framework to use.
     */
    public enum InferenceFramework {

        @JsonProperty("mlx") MLX,
        @JsonProperty("transformers") TRANSFORMERS,
        @JsonProperty("vllm") VLLM

    }

    /**
     * Type of transformers auto-model to use.
     */
    public enum TransformersModelType {

        @JsonProperty("automodel") AUTOMODEL,
        @JsonProperty("automodel-vision2seq") AUTOMODEL_VISION2SEQ,
        @JsonProperty("automodel-causallm") AUTOMODEL_CAUSALLM,
        @JsonProperty("automodel-imagetexttotext") AUTOMODEL_IMAGETEXTTOTEXT

    }

}
